name: Generate Snake Animation

on:
  schedule: # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake GIF
    runs-on: ubuntu-latest

    steps:
      # Generate the snake.svg animation
      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: apolo-itnet
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the generated SVG to the output branch
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
